apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api-deployment
  labels:
    app: heart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: heart-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          # Opcional: recursos m√≠nimos
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
