apiVersion: v1
kind: Service
metadata:
  name: heart-api-service
  labels:
    app: heart-api
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
    - name: http
      port: 8000        # Puerto dentro del cluster
      targetPort: 8000  # Puerto del contenedor
      nodePort: 30000   # Puerto del nodo (host)
